[package]
name = "packer_project"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
lz4_flex = "0.11"
rand = "0.8.5"

[[bin]]
name = "stub"
path = "src/stub.rs"

[[bin]]
name = "packer"
path = "src/packer.rs"
