[package]
name = "stub"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
lz4_flex = "0.11"
aes = { path = "../aes" }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
whitebox = { path = "../whitebox" }
checksum = { path = "../checksum" }
