[package]
name = "website"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-multipart = "0.4"
futures = "0.3"
uuid = { version = "1", features = ["v4"] }
sanitize-filename = "0.3"
