name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: test cd
      run: cd rpack
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload rPack executable
      uses: actions/upload-artifact@v4
      with:
        name: rpack
        path: |
          rpack/target/debug/rpack
